name: Auto-merge dependabot updates
on:
  schedule:
    - cron: '0 5 * * *'
jobs:
  test:
    name: Auto-merge dependabot updates
    runs-on: ubuntu-latest
    steps:
      - uses: akheron/dependabot-cron-action@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
